#!perl

use strict;
use warnings FATAL => 'all';

use Test::More tests => 1;                      # last test to print

ok(1);

__END__

#
#===============================================================================
#
#         FILE:  |FILENAME|
#
#  DESCRIPTION:  |CURSOR|
#
#        FILES:  ---
#         BUGS:  ---
#        NOTES:  ---
#       AUTHOR:  |AUTHOR| (|AUTHORREF|), <|EMAIL|>
#      COMPANY:  |COMPANY|
#      VERSION:  1.0
#      CREATED:  |DATE|
#     REVISION:  ---
#===============================================================================
